name: alarm_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  alarm: ^4.1.1
  auto_start_flutter: ^0.1.3
  flutter:
    sdk: flutter
  hive_ce: ^2.8.0+3
  hive_ce_flutter: ^2.1.0
  
  intl: ^0.20.1
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_ce_generator: ^1.8.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - assets/alarm2.mp3
    - assets/alarm3.mp3
    - assets/alarm4.mp3
    - assets/alarm5.mp3
